### ISSUE TITLE
Add test that uses openssl app

### ISSUE THREAD

**Issue by daurnimator** [Netflix/bettertls#5]
I think the runner would be as simple as:

```
openssl s_client -capath ../certificates/root.crt -connect test.nameconstraints.bettertls.com:8244 
```

**Comment by JackOfMostTrades** [comment]
Good call. I needed to do a little bit of futzing to add a "-verify_hostname x" or "-verify_ip y" parameter as needed, but otherwise worked well enough. On first pass it was showing some false positive test results, but on review I saw that it was applying DNS name constraints against the CN even when the CN was an IP. Since using an IP in a CN isn't to-spec anyway I adjusted the test result expectations. With that sorted, OpenSSL has a 100% pass!
